Challenge Clase 26 - Eventos, QAM
AcamicaDWFS/Clase_26_Eventos pull request #5
Opened 2020-07-10 07:27 UTC by megumiEvans

2020-07-11 18:10 UTC, jomarguzman requested changes
El comportamiento es el adecuado para el ejercicio, la validación la esta realizando el form, ya que utilizaste el atributo **required**, para completar este challenge es necesario que la validación no se haga por medio de required.

2020-07-11 18:10 UTC, jomarguzman commented on Challenge/index.html
> +    </form>
Buen uso de los atrubutos de los elemetos de HTML

2020-07-11 18:10 UTC, jomarguzman commented on Challenge/index.html
> +<script src="script.js"></script>
Agregar esta linea dentro del body por buena práctica.

2020-07-11 18:10 UTC, jomarguzman commented on Challenge/script.js
> +	}else{
Excelente validación del contenido del input

2020-07-17 04:04 UTC, megumiEvans commented on Challenge/index.html
> +    </form>
:)

2020-07-17 04:04 UTC, megumiEvans commented on Challenge/index.html
> +<script src="script.js"></script>
Resuelto

2020-07-21 21:52 UTC, merged