Add files via upload
AcamicaDWFS/Clase_26_Eventos pull request #9
Opened 2020-07-10 23:15 UTC by lisvsz

Espero sus comentarios, gracias 🌮

2020-07-11 18:55 UTC, jomarguzman requested changes
El ejercicio debe de estar dentro de la carpeta challenge y dentro de ella la carpeta con tu nombre, agregar el addEventListener con el evento click

2020-07-11 18:55 UTC, jomarguzman commented on Challenge 26/index.html
> +    <button id = "btn1" onclick="hi()">Enviar</button>
Buen uso de elemtos y atributos del HTML, simplemente hay que tener cuidado ya que se puede utilizar un input text o un label en lugar de un p, la llamada a la funcion debe de ser por medio de addEventListener ya que onclick es un evento.

2020-07-11 18:55 UTC, jomarguzman commented on Challenge 26/main.js
> +
La validación y los mensajes mostrados con correctos, se hace uso de addEventListener para la interacción con el teclado.

2020-07-20 23:24 UTC, lisvsz commented on Challenge 26/index.html
> +    <button id = "btn1" onclick="hi()">Enviar</button>
Entendido, ya lo cambié :D gracias!

2020-07-20 23:31 UTC, merged